### PR TITLE
Aw 5 build the landing page header

### PR DESCRIPTION
**Pull request by eimaam**
## Description
Build the landing page 

## Jira Ticket 
[AW-5](https://eimaam-dev.atlassian.net/browse/AW-5)

[AW-5]: https://eimaam-dev.atlassian.net/browse/AW-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by JosephChuksN — COMMENTED** [review]
We are using Tailwind CSS for this project, we should stick to the standards of it calling whatever fonts we will be using from the CSS file.

The header component is missing the React.FC type since we are using typescript

**Comment by eimaam** [comment]
> We are using Tailwind CSS for this project, we should stick to the standards of it calling whatever fonts we will be using from the CSS file.
> 
> The header component is missing the React.FC type since we are using typescript

For the Fonts, that's what I did. Check the CSS file and it is defined there already. I used Tailwind for that.
For the React.FC, I did not use it for any of the components. You want us to use that feature?

**Review by JosephChuksN — APPROVED** [review]
how about we put the home components in a home folder for better clarification, so when trying to fix an issue we know what folder location we should be dealing with

**Comment by eimaam** [comment]
> how about we put the home components in a home folder for better clarification, so when trying to fix an issue we know what folder location we should be dealing with

Created Home component in `pages` folder... And I'd be importing the header component into it then you import the other components you are working on from `components` folder.

**Pull request merged**
